user:
  validation:
    name_max: 50
    email_max: 255
    pass_min: 8
  format:
    email: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  index_page: 15
home:
  path_img: "logo.jpg"
users_helper:
  size_img: 50
  size_img1: 35
product:
  validation:
    name_product: 50
    info: 255
cart_item:
  validation:
    greater: 0
reset_pass:
  expired: 2
