user:
  validation:
    name_max: 50
    email_max: 255
  format:
    email: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
product:
  validation:
    name_product: 50
    info: 255
